// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package users

import (
	"github.com/google/wire"
	"github.com/xans-me/authopia/app"
	"github.com/xans-me/authopia/core/configuration"
)

// Injectors from wire.go:

func InjectRPC() (*RpcDelivery, error) {
	environmentConfigBinderProperties := _wireEnvironmentConfigBinderPropertiesValue
	appConfig := app.ProvideAppConfig(environmentConfigBinderProperties)
	keyCloak := app.ProvideKeycloakConfig(appConfig)
	repository := NewRepository(keyCloak)
	useCase := NewUseCase(repository, keyCloak)
	server := app.ProvideGRPC()
	rpcDelivery := NewRpcDelivery(useCase, server)
	return rpcDelivery, nil
}

var (
	_wireEnvironmentConfigBinderPropertiesValue = configuration.EnvironmentConfigBinderProperties{
		FileName: "app-config",
		Path:     "./env",
	}
)

// wire.go:

var (
	ModuleSet = wire.NewSet(
		NewRepository,
		NewUseCase, wire.Bind(new(IUseCase), new(*UseCase)), wire.Bind(new(IUsersRepository), new(*Repository)), NewRpcDelivery)
)
