app:
  name: AUTHOPIA
  environment: local
  host: 0.0.0.0
  debug: true
  port: 9090
  protocol: tcp4
keyCloak:
  baseUrlAuth: http://localhost:8080
  Realm: Development-CT
  AdminUsername: admin
  AdminPassword: password
  ClientID: "account"
  ClientSecret: "sk2pWyqaRxN3Ho1cawnWp5qSDTZYS1Kn"
sqlDatabase:
  connection: postgres
  name: "development"
  user: "developmentUser"
  password: "password"
  port: 5432
  host: localhost
  MaximumOpenConnection: 100
  MaximumIdleConnection: 25
