app:
  name: AUTHOPIA
  environment: sandbox
  host: 0.0.0.0
  debug: true
  port: 3000
  protocol: tcp4
keyCloak:
  baseUrlAuth: http://localhost:8080
  Realm: "aphrodite-iam"
  ClientID: "aphrodite-be"
  ClientSecret: "ygDCwirAHjcvf5BWQcDGiYLmr3DMgFso"
  AdminUsername: ichsan.mulya@outlook.com
  AdminPassword: 00Exploit
sqlDatabase:
  connection: postgres
  name: "development"
  user: "developmentUser"
  password: "password"
  port: 5432
  host: localhost
  MaximumOpenConnection: 100
  MaximumIdleConnection: 25
